### PR TITLE
changed require to eval import

### PR DESCRIPTION
**Pull request by tbreloff**
This gets rid of a 0.4 deprecation warning for me... does it create any problems that I don't foresee?

### CODE REVIEW

**Comment by one-more-minute** [comment]
Seems reasonable to me. Note that I'm planning on removing this functionality in 0.4 though, since it's a bit redundant once you have precompilation, and I'm not that interested in maintaining it.

**Comment by tbreloff** [comment]
I'm not sure how precompilation makes this redundant. The huge advantage of lazy loading of packages is that you don't even need the package installed. My use case is in the Plots package I'm working on (
https://github.com/tbreloff/Plots.jl). The idea is that it will be a common interface for most plotting packages, but that a user might only have one or two of them installed. It also makes for minimal dependecies.

**Comment by one-more-minute** [comment]
`@lazymod` was really designed to lazy load code within a single package, e.g. [like this](https://github.com/one-more-minute/Jewel.jl/blob/0e28dfbd5dcfbf31bd64a9eedf0a9882f3f0a175/src/Jewel.jl#L12). Hence it being redundant in 0.4 – it actually prevents precompilation of ProfileView which makes loading slower, if anything.

In your case, I suspect that using `@lazymod` is making things more complicated, not less. You could replace your call to `gadfly()` with a simple `@eval import Gadfly`. Then you should be able to remove the `global Gadfly = Main.Gadfly` as well.

**Comment by tbreloff** [comment]
I actually realized this a minute ago, and was about to post roughly the same thing. I'm going to swap out the calls as you described. Thanks!

**Pull request merged**
